[32m[INFO ][m [35m[2023-03-31T09:08:57,580] [background-preinit] [Version][m HV000001: Hibernate Validator 6.2.3.Final 
[32m[INFO ][m [35m[2023-03-31T09:08:57,602] [main] [Application][m Starting Application using Java 17.0.6 on 192.168.1.9 with PID 38628 (/home/hpca/ddev/interview-pleno/core/target/classes started by root in /home/hpca/ddev/interview-pleno/core) 
[32m[INFO ][m [35m[2023-03-31T09:08:57,604] [main] [Application][m No active profile set, falling back to 1 default profile: "default" 
[32m[INFO ][m [35m[2023-03-31T09:08:57,896] [main] [RepositoryConfigurationDelegate][m Bootstrapping Spring Data JDBC repositories in DEFAULT mode. 
[32m[INFO ][m [35m[2023-03-31T09:08:57,903] [main] [RepositoryConfigurationDelegate][m Finished Spring Data repository scanning in 3 ms. Found 0 JDBC repository interfaces. 
[32m[INFO ][m [35m[2023-03-31T09:08:58,206] [main] [TomcatWebServer][m Tomcat initialized with port(s): 8080 (http) 
[32m[INFO ][m [35m[2023-03-31T09:08:58,220] [main] [Http11NioProtocol][m The ["http-nio-8080"] connector has been configured to support HTTP upgrade to [h2c] 
[32m[INFO ][m [35m[2023-03-31T09:08:58,220] [main] [Http11NioProtocol][m Initializing ProtocolHandler ["http-nio-8080"] 
[32m[INFO ][m [35m[2023-03-31T09:08:58,221] [main] [StandardService][m Starting service [Tomcat] 
[32m[INFO ][m [35m[2023-03-31T09:08:58,221] [main] [StandardEngine][m Starting Servlet engine: [Apache Tomcat/9.0.62] 
[32m[INFO ][m [35m[2023-03-31T09:08:58,268] [main] [[/]][m Initializing Spring embedded WebApplicationContext 
[32m[INFO ][m [35m[2023-03-31T09:08:58,268] [main] [ServletWebServerApplicationContext][m Root WebApplicationContext: initialization completed in 639 ms 
[32m[INFO ][m [35m[2023-03-31T09:08:58,353] [main] [HikariDataSource][m HikariPool-1 - Starting... 
[1;31m[ERROR][m [35m[2023-03-31T09:08:59,409] [main] [HikariPool][m HikariPool-1 - Exception during pool initialization. 
org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:319) ~[postgresql-42.3.4.jar:42.3.4]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49) ~[postgresql-42.3.4.jar:42.3.4]
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223) ~[postgresql-42.3.4.jar:42.3.4]
	at org.postgresql.Driver.makeConnection(Driver.java:402) ~[postgresql-42.3.4.jar:42.3.4]
	at org.postgresql.Driver.connect(Driver.java:261) ~[postgresql-42.3.4.jar:42.3.4]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[HikariCP-4.0.3.jar:?]
	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:52) ~[flyway-core-8.0.5.jar:?]
	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:74) ~[flyway-core-8.0.5.jar:?]
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:143) ~[flyway-core-8.0.5.jar:?]
	at org.flywaydb.core.Flyway.migrate(Flyway.java:124) ~[flyway-core-8.0.5.jar:?]
	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66) ~[spring-boot-autoconfigure-2.6.7.jar:2.6.7]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.19.jar:5.3.19]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.19.jar:5.3.19]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.19.jar:5.3.19]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.19.jar:5.3.19]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.19.jar:5.3.19]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.19.jar:5.3.19]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.19.jar:5.3.19]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.19.jar:5.3.19]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.3.19.jar:5.3.19]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.19.jar:5.3.19]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953) ~[spring-beans-5.3.19.jar:5.3.19]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.19.jar:5.3.19]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.19.jar:5.3.19]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.6.7.jar:2.6.7]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:740) ~[spring-boot-2.6.7.jar:2.6.7]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:415) ~[spring-boot-2.6.7.jar:2.6.7]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) ~[spring-boot-2.6.7.jar:2.6.7]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1312) ~[spring-boot-2.6.7.jar:2.6.7]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301) ~[spring-boot-2.6.7.jar:2.6.7]
	at br.com.gubee.interview.core.Application.main(Application.java:12) ~[classes/:?]
Caused by: java.net.ConnectException: Conex√£o recusada
	at sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
	at sun.nio.ch.Net.pollConnectNow(Net.java:672) ~[?:?]
	at sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:633) ~[?:?]
	at org.postgresql.core.PGStream.createSocket(PGStream.java:241) ~[postgresql-42.3.4.jar:42.3.4]
	at org.postgresql.core.PGStream.<init>(PGStream.java:98) ~[postgresql-42.3.4.jar:42.3.4]
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:109) ~[postgresql-42.3.4.jar:42.3.4]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:235) ~[postgresql-42.3.4.jar:42.3.4]
	... 36 more
[33m[WARN ][m [35m[2023-03-31T09:08:59,464] [main] [AnnotationConfigServletWebServerApplicationContext][m Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.internal.exception.FlywaySqlException: Unable to obtain connection from database: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 08001
Error Code : 0
Message    : Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
 
[32m[INFO ][m [35m[2023-03-31T09:08:59,466] [main] [StandardService][m Stopping service [Tomcat] 
[32m[INFO ][m [35m[2023-03-31T09:08:59,473] [main] [ConditionEvaluationReportLoggingListener][m 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled. 
[1;31m[ERROR][m [35m[2023-03-31T09:08:59,481] [main] [SpringApplication][m Application run failed 
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.internal.exception.FlywaySqlException: Unable to obtain connection from database: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 08001
Error Code : 0
Message    : Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804) ~[spring-beans-5.3.19.jar:5.3.19]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.19.jar:5.3.19]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.19.jar:5.3.19]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.19.jar:5.3.19]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.19.jar:5.3.19]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.19.jar:5.3.19]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.19.jar:5.3.19]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.3.19.jar:5.3.19]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.19.jar:5.3.19]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953) ~[spring-beans-5.3.19.jar:5.3.19]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.19.jar:5.3.19]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.19.jar:5.3.19]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.6.7.jar:2.6.7]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:740) ~[spring-boot-2.6.7.jar:2.6.7]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:415) ~[spring-boot-2.6.7.jar:2.6.7]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) ~[spring-boot-2.6.7.jar:2.6.7]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1312) ~[spring-boot-2.6.7.jar:2.6.7]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301) ~[spring-boot-2.6.7.jar:2.6.7]
	at br.com.gubee.interview.core.Application.main(Application.java:12) ~[classes/:?]
Caused by: org.flywaydb.core.internal.exception.FlywaySqlException: Unable to obtain connection from database: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 08001
Error Code : 0
Message    : Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.

	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:67) ~[flyway-core-8.0.5.jar:?]
	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:74) ~[flyway-core-8.0.5.jar:?]
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:143) ~[flyway-core-8.0.5.jar:?]
	at org.flywaydb.core.Flyway.migrate(Flyway.java:124) ~[flyway-core-8.0.5.jar:?]
	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66) ~[spring-boot-autoconfigure-2.6.7.jar:2.6.7]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.19.jar:5.3.19]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.19.jar:5.3.19]
	... 18 more
Caused by: org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:319) ~[postgresql-42.3.4.jar:42.3.4]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49) ~[postgresql-42.3.4.jar:42.3.4]
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223) ~[postgresql-42.3.4.jar:42.3.4]
	at org.postgresql.Driver.makeConnection(Driver.java:402) ~[postgresql-42.3.4.jar:42.3.4]
	at org.postgresql.Driver.connect(Driver.java:261) ~[postgresql-42.3.4.jar:42.3.4]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[HikariCP-4.0.3.jar:?]
	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:52) ~[flyway-core-8.0.5.jar:?]
	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:74) ~[flyway-core-8.0.5.jar:?]
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:143) ~[flyway-core-8.0.5.jar:?]
	at org.flywaydb.core.Flyway.migrate(Flyway.java:124) ~[flyway-core-8.0.5.jar:?]
	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66) ~[spring-boot-autoconfigure-2.6.7.jar:2.6.7]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.19.jar:5.3.19]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.19.jar:5.3.19]
	... 18 more
Caused by: java.net.ConnectException: Conex√£o recusada
	at sun.nio.ch.Net.pollConnect(Native Method) ~[?:?]
	at sun.nio.ch.Net.pollConnectNow(Net.java:672) ~[?:?]
	at sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542) ~[?:?]
	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597) ~[?:?]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
	at java.net.Socket.connect(Socket.java:633) ~[?:?]
	at org.postgresql.core.PGStream.createSocket(PGStream.java:241) ~[postgresql-42.3.4.jar:42.3.4]
	at org.postgresql.core.PGStream.<init>(PGStream.java:98) ~[postgresql-42.3.4.jar:42.3.4]
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:109) ~[postgresql-42.3.4.jar:42.3.4]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:235) ~[postgresql-42.3.4.jar:42.3.4]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49) ~[postgresql-42.3.4.jar:42.3.4]
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223) ~[postgresql-42.3.4.jar:42.3.4]
	at org.postgresql.Driver.makeConnection(Driver.java:402) ~[postgresql-42.3.4.jar:42.3.4]
	at org.postgresql.Driver.connect(Driver.java:261) ~[postgresql-42.3.4.jar:42.3.4]
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:364) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[HikariCP-4.0.3.jar:?]
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:112) ~[HikariCP-4.0.3.jar:?]
	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:52) ~[flyway-core-8.0.5.jar:?]
	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:74) ~[flyway-core-8.0.5.jar:?]
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:143) ~[flyway-core-8.0.5.jar:?]
	at org.flywaydb.core.Flyway.migrate(Flyway.java:124) ~[flyway-core-8.0.5.jar:?]
	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66) ~[spring-boot-autoconfigure-2.6.7.jar:2.6.7]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.19.jar:5.3.19]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.19.jar:5.3.19]
	... 18 more
[32m[INFO ][m [35m[2023-03-31T09:39:14,326] [background-preinit] [Version][m HV000001: Hibernate Validator 6.2.3.Final 
[32m[INFO ][m [35m[2023-03-31T09:39:14,348] [main] [Application][m Starting Application using Java 17.0.6 on 192.168.1.9 with PID 50503 (/home/hpca/ddev/interview-pleno/core/target/classes started by root in /home/hpca/ddev/interview-pleno/core) 
[32m[INFO ][m [35m[2023-03-31T09:39:14,350] [main] [Application][m No active profile set, falling back to 1 default profile: "default" 
[32m[INFO ][m [35m[2023-03-31T09:39:14,665] [main] [RepositoryConfigurationDelegate][m Bootstrapping Spring Data JDBC repositories in DEFAULT mode. 
[32m[INFO ][m [35m[2023-03-31T09:39:14,671] [main] [RepositoryConfigurationDelegate][m Finished Spring Data repository scanning in 3 ms. Found 0 JDBC repository interfaces. 
[32m[INFO ][m [35m[2023-03-31T09:39:14,936] [main] [TomcatWebServer][m Tomcat initialized with port(s): 8080 (http) 
[32m[INFO ][m [35m[2023-03-31T09:39:14,946] [main] [Http11NioProtocol][m The ["http-nio-8080"] connector has been configured to support HTTP upgrade to [h2c] 
[32m[INFO ][m [35m[2023-03-31T09:39:14,947] [main] [Http11NioProtocol][m Initializing ProtocolHandler ["http-nio-8080"] 
[32m[INFO ][m [35m[2023-03-31T09:39:14,948] [main] [StandardService][m Starting service [Tomcat] 
[32m[INFO ][m [35m[2023-03-31T09:39:14,948] [main] [StandardEngine][m Starting Servlet engine: [Apache Tomcat/9.0.62] 
[32m[INFO ][m [35m[2023-03-31T09:39:14,995] [main] [[/]][m Initializing Spring embedded WebApplicationContext 
[32m[INFO ][m [35m[2023-03-31T09:39:14,995] [main] [ServletWebServerApplicationContext][m Root WebApplicationContext: initialization completed in 621 ms 
[33m[WARN ][m [35m[2023-03-31T09:39:15,171] [main] [AnnotationConfigServletWebServerApplicationContext][m Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Factory method 'dataSource' threw exception; nested exception is org.springframework.boot.autoconfigure.jdbc.DataSourceProperties$DataSourceBeanCreationException: Failed to determine a suitable driver class 
[32m[INFO ][m [35m[2023-03-31T09:39:15,208] [main] [StandardService][m Stopping service [Tomcat] 
[32m[INFO ][m [35m[2023-03-31T09:39:15,216] [main] [ConditionEvaluationReportLoggingListener][m 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled. 
[1;31m[ERROR][m [35m[2023-03-31T09:39:15,225] [main] [LoggingFailureAnalysisReporter][m 

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class


Action:

Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).
 
[32m[INFO ][m [35m[2023-03-31T09:40:44,757] [background-preinit] [Version][m HV000001: Hibernate Validator 6.2.3.Final 
[32m[INFO ][m [35m[2023-03-31T09:40:44,781] [main] [Application][m Starting Application using Java 17.0.6 on 192.168.1.9 with PID 51274 (/home/hpca/ddev/interview-pleno/core/target/classes started by root in /home/hpca/ddev/interview-pleno/core) 
[32m[INFO ][m [35m[2023-03-31T09:40:44,784] [main] [Application][m No active profile set, falling back to 1 default profile: "default" 
[32m[INFO ][m [35m[2023-03-31T09:40:45,097] [main] [RepositoryConfigurationDelegate][m Bootstrapping Spring Data JDBC repositories in DEFAULT mode. 
[32m[INFO ][m [35m[2023-03-31T09:40:45,104] [main] [RepositoryConfigurationDelegate][m Finished Spring Data repository scanning in 4 ms. Found 0 JDBC repository interfaces. 
[32m[INFO ][m [35m[2023-03-31T09:40:45,381] [main] [TomcatWebServer][m Tomcat initialized with port(s): 8080 (http) 
[32m[INFO ][m [35m[2023-03-31T09:40:45,392] [main] [Http11NioProtocol][m The ["http-nio-8080"] connector has been configured to support HTTP upgrade to [h2c] 
[32m[INFO ][m [35m[2023-03-31T09:40:45,392] [main] [Http11NioProtocol][m Initializing ProtocolHandler ["http-nio-8080"] 
[32m[INFO ][m [35m[2023-03-31T09:40:45,393] [main] [StandardService][m Starting service [Tomcat] 
[32m[INFO ][m [35m[2023-03-31T09:40:45,393] [main] [StandardEngine][m Starting Servlet engine: [Apache Tomcat/9.0.62] 
[32m[INFO ][m [35m[2023-03-31T09:40:45,438] [main] [[/]][m Initializing Spring embedded WebApplicationContext 
[32m[INFO ][m [35m[2023-03-31T09:40:45,438] [main] [ServletWebServerApplicationContext][m Root WebApplicationContext: initialization completed in 627 ms 
[33m[WARN ][m [35m[2023-03-31T09:40:45,615] [main] [AnnotationConfigServletWebServerApplicationContext][m Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Factory method 'dataSource' threw exception; nested exception is org.springframework.boot.autoconfigure.jdbc.DataSourceProperties$DataSourceBeanCreationException: Failed to determine a suitable driver class 
[32m[INFO ][m [35m[2023-03-31T09:40:45,653] [main] [StandardService][m Stopping service [Tomcat] 
[32m[INFO ][m [35m[2023-03-31T09:40:45,662] [main] [ConditionEvaluationReportLoggingListener][m 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled. 
[1;31m[ERROR][m [35m[2023-03-31T09:40:45,671] [main] [LoggingFailureAnalysisReporter][m 

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class


Action:

Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).
 
[32m[INFO ][m [35m[2023-03-31T09:41:09,755] [background-preinit] [Version][m HV000001: Hibernate Validator 6.2.3.Final 
[32m[INFO ][m [35m[2023-03-31T09:41:09,777] [main] [Application][m Starting Application using Java 17.0.6 on 192.168.1.9 with PID 51582 (/home/hpca/ddev/interview-pleno/core/target/classes started by root in /home/hpca/ddev/interview-pleno/core) 
[32m[INFO ][m [35m[2023-03-31T09:41:09,779] [main] [Application][m No active profile set, falling back to 1 default profile: "default" 
[32m[INFO ][m [35m[2023-03-31T09:41:10,064] [main] [RepositoryConfigurationDelegate][m Bootstrapping Spring Data JDBC repositories in DEFAULT mode. 
[32m[INFO ][m [35m[2023-03-31T09:41:10,070] [main] [RepositoryConfigurationDelegate][m Finished Spring Data repository scanning in 3 ms. Found 0 JDBC repository interfaces. 
[32m[INFO ][m [35m[2023-03-31T09:41:10,337] [main] [TomcatWebServer][m Tomcat initialized with port(s): 8080 (http) 
[32m[INFO ][m [35m[2023-03-31T09:41:10,347] [main] [Http11NioProtocol][m The ["http-nio-8080"] connector has been configured to support HTTP upgrade to [h2c] 
[32m[INFO ][m [35m[2023-03-31T09:41:10,347] [main] [Http11NioProtocol][m Initializing ProtocolHandler ["http-nio-8080"] 
[32m[INFO ][m [35m[2023-03-31T09:41:10,348] [main] [StandardService][m Starting service [Tomcat] 
[32m[INFO ][m [35m[2023-03-31T09:41:10,348] [main] [StandardEngine][m Starting Servlet engine: [Apache Tomcat/9.0.62] 
[32m[INFO ][m [35m[2023-03-31T09:41:10,393] [main] [[/]][m Initializing Spring embedded WebApplicationContext 
[32m[INFO ][m [35m[2023-03-31T09:41:10,393] [main] [ServletWebServerApplicationContext][m Root WebApplicationContext: initialization completed in 592 ms 
[33m[WARN ][m [35m[2023-03-31T09:41:10,567] [main] [AnnotationConfigServletWebServerApplicationContext][m Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Factory method 'dataSource' threw exception; nested exception is org.springframework.boot.autoconfigure.jdbc.DataSourceProperties$DataSourceBeanCreationException: Failed to determine a suitable driver class 
[32m[INFO ][m [35m[2023-03-31T09:41:10,604] [main] [StandardService][m Stopping service [Tomcat] 
[32m[INFO ][m [35m[2023-03-31T09:41:10,613] [main] [ConditionEvaluationReportLoggingListener][m 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled. 
[1;31m[ERROR][m [35m[2023-03-31T09:41:10,621] [main] [LoggingFailureAnalysisReporter][m 

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class


Action:

Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).
 
[32m[INFO ][m [35m[2023-03-31T09:44:18,876] [background-preinit] [Version][m HV000001: Hibernate Validator 6.2.3.Final 
[32m[INFO ][m [35m[2023-03-31T09:44:18,898] [main] [Application][m Starting Application using Java 17.0.6 on 192.168.1.9 with PID 52731 (/home/hpca/ddev/interview-pleno/core/target/classes started by root in /home/hpca/ddev/interview-pleno/core) 
[32m[INFO ][m [35m[2023-03-31T09:44:18,900] [main] [Application][m No active profile set, falling back to 1 default profile: "default" 
[32m[INFO ][m [35m[2023-03-31T09:44:19,190] [main] [RepositoryConfigurationDelegate][m Bootstrapping Spring Data JDBC repositories in DEFAULT mode. 
[32m[INFO ][m [35m[2023-03-31T09:44:19,196] [main] [RepositoryConfigurationDelegate][m Finished Spring Data repository scanning in 3 ms. Found 0 JDBC repository interfaces. 
[32m[INFO ][m [35m[2023-03-31T09:44:19,462] [main] [TomcatWebServer][m Tomcat initialized with port(s): 8080 (http) 
[32m[INFO ][m [35m[2023-03-31T09:44:19,473] [main] [Http11NioProtocol][m The ["http-nio-8080"] connector has been configured to support HTTP upgrade to [h2c] 
[32m[INFO ][m [35m[2023-03-31T09:44:19,473] [main] [Http11NioProtocol][m Initializing ProtocolHandler ["http-nio-8080"] 
[32m[INFO ][m [35m[2023-03-31T09:44:19,474] [main] [StandardService][m Starting service [Tomcat] 
[32m[INFO ][m [35m[2023-03-31T09:44:19,474] [main] [StandardEngine][m Starting Servlet engine: [Apache Tomcat/9.0.62] 
[32m[INFO ][m [35m[2023-03-31T09:44:19,523] [main] [[/]][m Initializing Spring embedded WebApplicationContext 
[32m[INFO ][m [35m[2023-03-31T09:44:19,523] [main] [ServletWebServerApplicationContext][m Root WebApplicationContext: initialization completed in 600 ms 
[33m[WARN ][m [35m[2023-03-31T09:44:19,711] [main] [AnnotationConfigServletWebServerApplicationContext][m Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfiguration$Hikari.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.zaxxer.hikari.HikariDataSource]: Factory method 'dataSource' threw exception; nested exception is org.springframework.boot.autoconfigure.jdbc.DataSourceProperties$DataSourceBeanCreationException: Failed to determine a suitable driver class 
[32m[INFO ][m [35m[2023-03-31T09:44:19,748] [main] [StandardService][m Stopping service [Tomcat] 
[32m[INFO ][m [35m[2023-03-31T09:44:19,757] [main] [ConditionEvaluationReportLoggingListener][m 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled. 
[1;31m[ERROR][m [35m[2023-03-31T09:44:19,767] [main] [LoggingFailureAnalysisReporter][m 

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class


Action:

Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).
 
